-- MySQL Script generated by MySQL Workbench
-- Sat Mar 26 20:49:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Task13
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Task13` ;

-- -----------------------------------------------------
-- Schema Task13
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Task13` DEFAULT CHARACTER SET utf8 ;
USE `Task13` ;

-- -----------------------------------------------------
-- Table `Task13`.`vaccine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task13`.`vaccine` ;

CREATE TABLE IF NOT EXISTS `Task13`.`vaccine` (
  `vaccine_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `manufacturing_date` DATE NOT NULL,
  `shelf_life` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`vaccine_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task13`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task13`.`group` ;

CREATE TABLE IF NOT EXISTS `Task13`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number_of_children` INT NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task13`.`child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task13`.`child` ;

CREATE TABLE IF NOT EXISTS `Task13`.`child` (
  `child_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`child_id`, `group_id`),
  INDEX `fk_child_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_child_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `Task13`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task13`.`vaccinated`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task13`.`vaccinated` ;

CREATE TABLE IF NOT EXISTS `Task13`.`vaccinated` (
  `vaccinated_id` INT NOT NULL AUTO_INCREMENT,
  `vaccine_id` INT NOT NULL,
  `child_id` INT NOT NULL,
  `vaccinated_date` DATE NOT NULL,
  PRIMARY KEY (`vaccinated_id`, `vaccine_id`, `child_id`),
  INDEX `fk_vaccinated_vaccine_idx` (`vaccine_id` ASC) VISIBLE,
  INDEX `fk_vaccinated_child1_idx` (`child_id` ASC) VISIBLE,
  CONSTRAINT `fk_vaccinated_vaccine`
    FOREIGN KEY (`vaccine_id`)
    REFERENCES `Task13`.`vaccine` (`vaccine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccinated_child1`
    FOREIGN KEY (`child_id`)
    REFERENCES `Task13`.`child` (`child_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task13`.`manufacture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task13`.`manufacture` ;

CREATE TABLE IF NOT EXISTS `Task13`.`manufacture` (
  `manufacture_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adrress` VARCHAR(45) NOT NULL,
  `certificate` INT NOT NULL,
  `specification` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manufacture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task13`.`manufacture_produce_vaccine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task13`.`manufacture_produce_vaccine` ;

CREATE TABLE IF NOT EXISTS `Task13`.`manufacture_produce_vaccine` (
  `manufacture_id` INT NOT NULL,
  `vaccine_id` INT NOT NULL,
  PRIMARY KEY (`manufacture_id`, `vaccine_id`),
  INDEX `fk_manufacture_produce_vaccine_vaccine1_idx` (`vaccine_id` ASC) VISIBLE,
  CONSTRAINT `fk_manufacture_produce_vaccine_manufacture1`
    FOREIGN KEY (`manufacture_id`)
    REFERENCES `Task13`.`manufacture` (`manufacture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manufacture_produce_vaccine_vaccine1`
    FOREIGN KEY (`vaccine_id`)
    REFERENCES `Task13`.`vaccine` (`vaccine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
