-- MySQL Script generated by MySQL Workbench
-- Sat Mar 26 20:51:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Task14
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Task14` ;

-- -----------------------------------------------------
-- Schema Task14
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Task14` DEFAULT CHARACTER SET utf8 ;
USE `Task14` ;

-- -----------------------------------------------------
-- Table `Task14`.`trainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task14`.`trainer` ;

CREATE TABLE IF NOT EXISTS `Task14`.`trainer` (
  `trainer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `qualification` VARCHAR(45) NOT NULL,
  `birth_date` DATE NULL,
  PRIMARY KEY (`trainer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task14`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task14`.`student` ;

CREATE TABLE IF NOT EXISTS `Task14`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `trainer_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `trainer_id`),
  INDEX `fk_student_trainer_idx` (`trainer_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_trainer`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `Task14`.`trainer` (`trainer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task14`.`standard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task14`.`standard` ;

CREATE TABLE IF NOT EXISTS `Task14`.`standard` (
  `standard_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`standard_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task14`.`examinator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task14`.`examinator` ;

CREATE TABLE IF NOT EXISTS `Task14`.`examinator` (
  `examinator_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`examinator_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task14`.`result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task14`.`result` ;

CREATE TABLE IF NOT EXISTS `Task14`.`result` (
  `result_id` INT NOT NULL AUTO_INCREMENT,
  `passed_date` DATETIME NOT NULL,
  `mark` INT NOT NULL,
  `student_id` INT NOT NULL,
  `standard_id` INT NOT NULL,
  `examinator_id` INT NOT NULL,
  PRIMARY KEY (`result_id`, `student_id`, `standard_id`, `examinator_id`),
  INDEX `fk_result_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_result_standard1_idx` (`standard_id` ASC) VISIBLE,
  INDEX `fk_result_examinator1_idx` (`examinator_id` ASC) VISIBLE,
  CONSTRAINT `fk_result_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Task14`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_standard1`
    FOREIGN KEY (`standard_id`)
    REFERENCES `Task14`.`standard` (`standard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_examinator1`
    FOREIGN KEY (`examinator_id`)
    REFERENCES `Task14`.`examinator` (`examinator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
